### ISSUE TITLE
Not working - 918+, DSM 7.2-64570

### ISSUE THREAD

**Issue by jerrell851** [007revad/Synology_enable_M2_volume#102]
![2023-08-11_204225](https://github.com/007revad/Synology_enable_M2_volume/assets/61078121/9bed2ff8-3930-45ef-ae86-ae4bd02701b7)

![2023-08-11_203631](https://github.com/007revad/Synology_enable_M2_volume/assets/61078121/9fddf290-ae94-4fed-8041-f7afc995018b)

see picture.

**Comment by 007revad** [comment]
Did storage manager see the NVMe drives before you ran the scripts?

**Comment by jerrell851** [comment]
> Did storage manager see the NVMe drives before you ran the scripts?

no.but syno_hdd_db.sh scripts can see.

**Comment by 007revad** [comment]
Some people have had issues with 7.2 update 2 or 7.2 update 3 not seeing their NVMe drives.

Do you want to roll back to 7.2 update 1 and see if storage manager then shows your NVMe drives? You won't lose any settings or data.
1. Run https://github.com/007revad/Synology_DSM_reinstall 
2. Do a manual DSM install of [DSM 7.2 (with Update 1)](https://archive.synology.com/download/Os/DSM/7.2-64570-1-NanoPacked)

**Comment by jerrell851** [comment]
> Some people have had issues with 7.2 update 2 or 7.2 update 3 not seeing their NVMe drives.
> 
> Do you want to roll back to 7.2 update 1 and see if storage manager then shows your NVMe drives? You won't lose any settings or data.
> 
> 1. Run https://github.com/007revad/Synology_DSM_reinstall
> 2. Do a manual DSM install of [DSM 7.2 (with Update 1)](https://archive.synology.com/download/Os/DSM/7.2-64570-1-NanoPacked)

Followed the steps but the downgrade failed, including the script to upgrade to version 1.08.
1、run re-install scripts.
![2023-08-13_000706-1](https://github.com/007revad/Synology_enable_M2_volume/assets/61078121/5f4cfddd-7d1d-4479-a5f3-a041046f5a4f)

2、upload dsm os.([DS918+](https://archive.synology.cn/download/Os/DSM/7.2-64570-1-NanoPacked)
![2023-08-13_001106-2](https://github.com/007revad/Synology_enable_M2_volume/assets/61078121/62da48c4-e277-4a1a-a8e3-b12661ebf676)

3、wait restart
![2023-08-13_001228-3](https://github.com/007revad/Synology_enable_M2_volume/assets/61078121/2c6c5bf3-6e0b-43f6-9ab2-8946901f5e13)

4、After restarting, control panel information.
![2023-08-13_000503-4](https://github.com/007revad/Synology_enable_M2_volume/assets/61078121/3b8890a9-9264-49e8-8fd0-c1c4532ad1ec)

5、Run hdd.sh
![2023-08-13_001625-5](https://github.com/007revad/Synology_enable_M2_volume/assets/61078121/4c30ca03-9f57-4587-8b39-1398812c7761)

6、run enable.sh
![2023-08-13_002323-6](https://github.com/007revad/Synology_enable_M2_volume/assets/61078121/54e27e42-afa2-4a21-b981-a35d7118640a)

7、storage manager not NVMe drives
![2023-08-13_002323-7](https://github.com/007revad/Synology_enable_M2_volume/assets/61078121/f4557987-874a-4cd3-a9fc-b8329316dd15)

**Comment by 007revad** [comment]
What does the following command return:
`sudo -i nvme list`

Can you downgrade to DSM 7.2 (with Update 1) again but this time disable DSM Auto Updates and don't run the scripts.

1. Disable any schedules you have that run the scripts.
2. Disable DSM Auto Update via "Control Panel > Update & Restore > Update Settings > Notify me... > OK".
3. Run https://github.com/007revad/Synology_DSM_reinstall 
4. Do a manual DSM install of [DSM 7.2 (with Update 1)](https://archive.synology.com/download/Os/DSM/7.2-64570-1-NanoPacked)
5. After the DS918+ has rebooted check if storage manager shows the NVMe drives.

**If step 5 shows the NVMe drives**, then run syno_hdd_db script.

**Comment by 007revad** [comment]
Also, what does the following command return:
`ls /run/synostorage/disks`

And these:
```
ls /run/synostorage/disks/nvme0n1
ls /run/synostorage/disks/nvme1n1
```

**Comment by jerrell851** [comment]
> 以下命令返回什么： `sudo -i nvme list`
> 
> 您能否再次降级到 DSM 7.2（更新 1），但这次禁用 DSM 自动更新并且不运行脚本。
> 
> 1. 禁用运行脚本的任何计划。
> 2. 通过“控制面板”禁用 DSM 自动更新 > 更新和恢复>更新设置>通知我...> 好的”。
> 3. 运行 https://github.com/007revad/Synology_DSM_reinstall
> 4. 手动安装 [DSM 7.2（更新 1）](https://archive.synology.com/download/Os/DSM/7.2-64570-1-NanoPacked)
> 5. DS918+ 重新启动后，请检查存储管理器是否显示 NVMe 驱动器。
> 
> **如果步骤 5 显示 NVMe 驱动器，则**运行syno_hdd_db脚本。

Affected the use, test next time. But my downgrade steps are the same as you described, 1. disable automatic updates, 2. run the reinstall script, 3. manually install 7.2-64570-1-NanoPacked. However, the system information does not change to update 1.

**Comment by 007revad** [comment]
I just tested downgrading from **7.2 Update 2** to **7.2 (with Update 1)** and after it rebooted it had **7.2 Update 3** installed (even though I have DSM set to notify me instead of auto updating. It looks like Synology consider update 3 is a critical update and is forcing it on people when they update to DSM 7.2. 

I might try it again but this time with my Internet disconnected so it can't update to Update 3.

Do you have a real DS918+ or is DSM running in expenology?

What do each of the following commands return:

`sudo -i nvme list`

`ls /run/synostorage/disks`

`ls /run/synostorage/disks/nvme0n1`

`ls /run/synostorage/disks/nvme1n1`

`get_key_value /etc.defaults/synoinfo.conf support_m2_pool`

`get_key_value /etc/synoinfo.conf support_m2_pool`

`get_key_value /etc.defaults/synoinfo.conf supportnvme`

`get_key_value /etc/synoinfo.conf supportnvme`

**Comment by jerrell851** [comment]
i'm running expenology.

There is currently no 918 operating environment, so the command you gave cannot be tested.

**Comment by 007revad** [comment]
There's a post on the [xpenology forum here](https://xpenology.com/forum/topic/67891-dsm-install-ryzen-3200g/#comment-437476) that says Peter Suh's M SHELL for TCRP FRIEND **includes NVMe cache automatic recognition**.

**Comment by MeowPerth** [comment]
![image](https://github.com/007revad/Synology_enable_M2_volume/assets/49628341/f4febd1c-a5a3-4994-9cc4-e83537546c02)

I had the same problem and it didn't work properly after using the “Synology_enable_M2_volume”. At present, I am in the DSM 7.2-64570 Update 3 version. The information obtained by executing these commands is for your reference.

**Comment by 007revad** [comment]
The `0 @` drive model is a problem. I've seen something similar in syno_hdd_db before.

I'll create a debug version of the script so we can see where it's getting that `0 @` drive model from.

**Comment by MeowPerth** [comment]
> 驱动器模型有问题。我以前在syno_hdd_db看到过类似的东西。`0 @`
> 
> 我将创建脚本的调试版本，以便我们可以看到它从何处获取该驱动器模型。`0 @`


`0 @ 'should be the reason why the firmware of my hard disk has been flashed, which causes the HDD model to be recognized as `0 @'.
However, this hard disk can be recognized and used normally, and DSM can also recognize and use it.
![image](https://github.com/007revad/Synology_enable_M2_volume/assets/49628341/ba7f2e7e-b703-4256-97a3-001e9dff2d90)

**Comment by MeowPerth** [comment]
In addition, I would like to add some information: 
I also tried to use " Synology_M2_volume", and the script ran normally, but after restarting, it was the same as before, and M was not recognized.

**Comment by 007revad** [comment]
Did the NVMe drive show in storage manager before you updated to DSM 7.2 Update 3?

Do the following commands list your NVMe drive?

`ls /run/synostorage/disks`

`ls /sys/block | grep nvme`

**Comment by MeowPerth** [comment]
> 在您更新到 DSM 7.2 更新 3 之前，NVMe 驱动器是否显示在存储管理器中？
> 
> 以下命令是否列出您的 NVMe 驱动器？
> 
> `ls /run/synostorage/disks`
> 
> `ls /sys/block | grep nvme`
![image](https://github.com/007revad/Synology_enable_M2_volume/assets/49628341/e15cb619-641b-4830-92b0-04aefd263997)
None in synostorage, only HDD hard disk

**Comment by MeowPerth** [comment]
> > 在您更新到 DSM 7.2 更新 3 之前，NVMe 驱动器是否显示在存储管理器中？
> > 以下命令是否列出您的 NVMe 驱动器？
> > `ls /run/synostorage/disks`
> > `ls /sys/block | grep nvme`

 ![image](https://user-images.githubusercontent.com/49628341/269238838-e15cb619-641b-4830-92b0-04aefd263997.png)
 None in synostorage, only HDD hard disk

**Comment by 007revad** [comment]
Can you try running syno_hdd_db with the -n option

`./volume/OS/Script/syno_hdd_db.sh -n`

Then reboot.

**Comment by MeowPerth** [comment]
> Can you try running syno_hdd_db with the -n option
> 
> `./volume/OS/Script/syno_hdd_db.sh -n`
> 
> Then reboot.

![TTQARSIT9}T})VG)4_PJ@QB](https://github.com/007revad/Synology_enable_M2_volume/assets/49628341/8d49f2e7-4cf2-47b5-91d7-607e66b9c4e4)

NVME is also not working properly.
PS: I added a SATA SSD "S100Pro 1TB" and it works.

**Comment by 007revad** [comment]
Can you run this script and see if that makes the NVMe drive show in storage manager.
https://github.com/AuxXxilium/arc-extensions/blob/main/nvmecache/all/usr/sbin/nvmecache.sh 

![download_button](https://github.com/007revad/Synology_enable_M2_volume/assets/39733752/f550113a-9d7d-43c2-993a-b1c180a6181e)

**Comment by MeowPerth** [comment]
![image](https://github.com/007revad/Synology_enable_M2_volume/assets/49628341/8f403164-9a89-4ca6-a43e-e8697da11931)
![image](https://github.com/007revad/Synology_enable_M2_volume/assets/49628341/19652e44-4409-4eab-869a-08b6e7346f16)


It's working！It appears that “libsynonvme.so.1” must be modified.

**Comment by 007revad** [comment]
Excellent
