### ISSUE TITLE
about bc dependent 

### ISSUE THREAD

**Issue by wjz304** [007revad/Synology_enable_M2_volume#114]
https://github.com/007revad/Synology_enable_M2_volume/blob/96ecdb5225d2bfd9b9bec6284c796c138ed18920/syno_enable_m2_volume.sh#L157
If not have, would be better to directly download it?
`curl -kL https://raw.githubusercontent.com/007revad/Synology_enable_M2_volume/main/bin/bc -o /tmp/bc`

**Comment by wjz304** [comment]
https://github.com/007revad/Synology_enable_M2_volume/blob/96ecdb5225d2bfd9b9bec6284c796c138ed18920/syno_enable_m2_volume.sh#L392

Can we add a parameter to skip interaction?

**Comment by 007revad** [comment]
> If not have, would be better to directly download it?
> `curl -kL https://raw.githubusercontent.com/007revad/Synology_enable_M2_volume/main/bin/bc -o /tmp/bc`

Yes. I added /bin/bc recently so I could have the script download it but hadn't got around to editing the script yet.

**Comment by 007revad** [comment]
> Can we add a parameter to skip interaction?

Do you want to:
1. Skip interaction and have the script reboot the machine?
2. Or skip the rebootmsg function?

**Comment by wjz304** [comment]
> > Can we add a parameter to skip interaction?
> 
> Do you want to:
> 
> 1. Skip interaction and have the script reboot the machine?
> 2. Or skip the rebootmsg function?

I want both
![7@VLUAPVWIOIU}7S ZJ$VNF](https://github.com/007revad/Synology_enable_M2_volume/assets/5615843/023fac82-25b4-4fa4-90e8-a09080ffd28f)

**Comment by wjz304** [comment]
> > > > Can we add a parameter to skip interaction?
> > > 
> > > 
> > > Do you want to:
> > > 
> > > 1. Skip interaction and have the script reboot the machine?
> > > 2. Or skip the rebootmsg function?
> > 
> > 
> > I want both
> 
> You want to skip interaction and reboot the machine while not rebooting the machine? :)
> 
> Or do you want 2 parameters so you have choice to either:
> 
> * Reboot without interaction.
> * No interaction and no reboot.

`No interaction and no reboot.`

The main issue is that there is no way to interact in addons (services), so skipping interaction is a priority. 
As for restarting, from the user's subjective perspective, automatic restarting may not be good. So I think skipping the reboot should be good.

(Sorry, my English is very poor. I'm not sure if I can express myself clearly)

**Comment by 007revad** [comment]
Your English is good.

I've updated the script. https://github.com/007revad/Synology_enable_M2_volume/releases/tag/v1.0.10 

- Added -n, --noreboot option to not reboot after script has run (and not show interactive).
- Changed to download and install bc, if needed.

**Comment by wjz304** [comment]
Thx!, 
![33ZP(L0_BU5T9%IEMWO_`OE](https://github.com/007revad/Synology_enable_M2_volume/assets/5615843/4c75d763-74f0-4a20-b7df-ebea73faee90)
