### ISSUE TITLE
Drive Database outdated. can't recognize your drive

### ISSUE THREAD

**Issue by arkady2k** [007revad/Synology_enable_M2_volume#125]
Hi,

I followed your script and all worked great for a day, the following day I got a message:

**The drive database is outdate and cannot recognize one ore more of your synology drives. to ensure compatibility, update the database**

when I go to my drives I see the volume and pool all working fine, but in the Firmware version section I see this message:
**Unrecognized firmware version, please update the drive database.**

I ran your script again and it didn't do anything, saying everything is good.  

 how to get rid of this warning? will this impact my storage functionality?

**Comment by 007revad** [comment]
Run my [Synology_HDD_db](https://github.com/007revad/Synology_HDD_db) script with the -n option

`sudo -i /path-to-script/syno_hdd_db.sh -n`
