### ISSUE TITLE
[Question] Is s.m.a.r.t available?

### ISSUE THREAD

**Issue by lorenc-tomasz** [007revad/Synology_enable_M2_volume#126]
Hi,
just just the script on 1621+. Worked fine, but there is no S.M.A.R.T status. Wondering if it's normal?

**Comment by 007revad** [comment]
In DSM 7.2-64570 Synology removed S.M.A.R.T. testing for M.2 NVMe SSDs (so no S.M.A.R.T. history either).

**Comment by lorenc-tomasz** [comment]
OK :) I'm on DSM 7.2.1-69057 Update 1 so that's way there is no s.m.a.r.t info.
