### ISSUE TITLE
/bin/bc: line 1: syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by artemus717** [007revad/Synology_enable_M2_volume#127]
<img width="590" alt="图片" src="https://github.com/007revad/Synology_enable_M2_volume/assets/16465173/ffe75f87-95d7-4d37-9b6b-347c095ba350">

I download the script from github. Sure did not edit or open any file on my PC.

Seemed like there are something wrong for bc file.

I tried to use bc in bin/bc to replace /bin/bc. But /bin/bc will come back to the little one.

**Comment by artemus717** [comment]
I replace bc again and check the privilege of bc. This time it works.

**Comment by 007revad** [comment]
I notice bc was in /bin  My script installs bc in /usr/bin and then sets it as executable.

One of the Xpenology loaders installs bc in /bin and another Xpenology loader installs bc in /usr/bin which would explain why you have bc in /bin

I'll change my script to check if bc is in /bin and set it as executable if needed.
