### ISSUE TITLE
synonvme --get-location /dev/nvme0n1

### ISSUE THREAD

**Issue by artemus717** [007revad/Synology_enable_M2_volume#128]
Could you tell me how to check?

<img width="639" alt="图片" src="https://github.com/007revad/Synology_enable_M2_volume/assets/16465173/90940f6a-f5bc-4ee5-9410-c6d80e727820">

**Comment by artemus717** [comment]
I had already run the script and reboot xpenology.

**Comment by 007revad** [comment]
Is the NVMe drive in a M.2 slot on the motherboard or in a PCIe card?

**Comment by artemus717** [comment]
> Is the NVMe drive in a M.2 slot on the motherboard or in a PCIe card?

PCI-E Card.

**Comment by artemus717** [comment]
I will try to edit /lib64/libsynonvme.so.1 tonight

https://wp.gxnas.com/10930.html/comment-page-2#comments

**Comment by artemus717** [comment]
<img width="1034" alt="image" src="https://github.com/007revad/Synology_enable_M2_volume/assets/16465173/07bb45b0-f586-4489-b226-10fa2716a36d">

**Comment by artemus717** [comment]
There are no pci-e slot config in libsynonvme.so.1

**Comment by artemus717** [comment]
Upgraded to latest 23.10.4 and latest addon modules, resolved.
