### ISSUE TITLE
Works on my DS 920+ 7.2.1-69057 Update 3 

### ISSUE THREAD

**Issue by thetigeregg** [007revad/Synology_enable_M2_volume#143]
Meant to update to 7.2.1-69057 Update 1 but got Update 3 instead. Upon first boot after updating DSM, the M2 volume was unrecognized, and DSM was complaining about it. I rebooted again and every was good again. I have a task scheduled to run this script (and the DB script) on shutdown, so that's probably why.

**Comment by 007revad** [comment]
DSM has a setting to enable/disable minor updates when installing DSM... but Synology can override the setting if they think the minor update is important. The only way to prevent it is to disconnect your router from the Internet once the DSM update has started (it needs an Internet connection to start the update). 

I edited the title to change "me" to "my" for you 😄
