### ISSUE TITLE
DSM 7.2.1-69057 Update 4 for DS920+

### ISSUE THREAD

**Issue by m04ndj5xc2u3pn4eow** [007revad/Synology_enable_M2_volume#161]
Hi,

I noticed **DSM 7.2.1-69057 Update 4** isn't listed in the "Confirmed working on" data table for the DS920+. 

Is it due to the version not being compatible with this script or it hasn't been tested yet?

Thanks again for creating this script!

**Comment by 007revad** [comment]
It's just that nobody with a DS920+ using DSM 7.2.1-69057 Update 4 has taken the time to report that it worked.

**Comment by m04ndj5xc2u3pn4eow** [comment]
I see. I’ll update now and provide you an answer.

**Comment by m04ndj5xc2u3pn4eow** [comment]
Confirming all is well with DSM 7.2.1-69057 Update 4 on DS920+ 👍
