### ISSUE TITLE
Script Syntax error line 161

### ISSUE THREAD

**Issue by aferende** [007revad/Synology_enable_M2_volume#166]
Hi Dave,
in the latest version I have this error:

`line 161: syntax error near unexpected token `)'`

Ty for your work.
Andrea.

**Comment by 007revad** [comment]
Thanks Andrea

I've deleted v1.1.20 and replaced it with a fixed v1.1.21
https://github.com/007revad/Synology_enable_M2_volume/releases

Synology_enable_Deduplication had the same bug so I've deleted v1.3.24 and replaced it with a fixed v1.3.25
https://github.com/007revad/Synology_enable_Deduplication/releases

**Comment by aferende** [comment]
Now working fine.
Thx
