### ISSUE TITLE
Sharing test results for all models in DSM 7.2.1-69057 Update 4

### ISSUE THREAD

**Issue by PeterSuh-Q3** [007revad/Synology_enable_M2_volume#168]
I have tested all models supported by Redpill in DSM 7.2.1-69057 Update 4 (based on TCRP).
TCRP supports a total of 9 platforms that support Epyc7002.
Among them, DS3615xs (Bromallow) was discontinued in 7.1.1.
As of now, DSM 7.2.1 brings the total to 8 platforms.

I supplemented it further by referring to your results sheet.
I added the results of the new working SA6400 and the non-working DS3615xs and DVA3221, and tested all of DSM 7.2.1-69057 Update 4.

All Broadwillnks do not work as expected except for the special DS1621xs+ which I discussed with you last time.

https://github.com/PeterSuh-Q3/tcrp-addons/tree/main/nvmevolume-onthefly#readme

I simplified the hexa patching of libhwcontrol.so.1 further as shown below.
This is similar to the method I used with my nvme-cache addon.

https://github.com/PeterSuh-Q3/tcrp-addons/blob/main/nvmevolume-onthefly/src/install.sh

Due to the nature of Redpill, it needs to be activated immediately after DSM installation is completed and the logon account is created, so the OS ON LOAD point where tmpRoot is used was used.

My script also operates in the same way as your result sheet regarding whether each model operates or not.

**Comment by PeterSuh-Q3** [comment]
In the case of DSM 1019+, NVMe cache must be activated with the Hexa patch in the libsynonvme.so.1 file, and only one can be used.

# |       models      |     1st      |     2nd      |
# | DS918+            | 0000:00:13.1 | 0000:00:13.2 |
# | RS1619xs+         | 0000:00:03.2 | 0000:00:03.3 |
# | DS419+, DS1019+   | 0000:00:14.1 |              |
# | DS719+, DS1621xs+ | 0000:00:01.1 | 0000:00:01.0 |

**Comment by 19jm81** [comment]
Any news on DSM 7.2.1-69057 Update 5?

**Comment by 007revad** [comment]
@19jm81 

DSM 7.2.1-69057 Update 5 should not be a problem because the only change Synology made was to fix a bug that prevented 7.2.1-69057 Update 4 updating to 7.2.2 (which hasn't been released yet).
