### ISSUE TITLE
DSM 7.2.1-69057 Update 5 not working

### ISSUE THREAD

**Issue by Deftone-Squad** [007revad/Synology_enable_M2_volume#177]
Hi there, it looks like the "Synology enable M2 volume" script is not working with the DSM 7.2.1-69057 Update 5 on the DS1821+.
I tried it several times with the tasked schedule in combination of the hdd vendor script but it's not working. 
Is there an update in the work? 
Regards

**Comment by 007revad** [comment]
You don't need "Synology enable M2 volume" on a DS1821+. You only need "Synology_HDD_db".

1.  Disable your "Synology enable M2 volume" scheduled task if you have it scheduled.
2. Run syno_enable_m2_volume.sh with the -r or --restore option to undo the changes it made
    -  `syno_enable_m2_volume.sh -r`
4. Then reboot.

**Comment by Deftone-Squad** [comment]
Ok just to make clear I have 2 DS1821+.
On Nr. 1 I added the scheduled task to Update 4 and then updated to 5 --> worked.
On Nr. 2 I added the scheduled task after updated to 5 --> not working.

I now have added --restore to the scheduled path which looks like this:

/volume2/Synology Scripts/Synology_HDD_db/Synology_HDD_db-3.5.89/syno_hdd_db.sh --restore

On both DS1821+ this leads to no change at all.

Is there a limit in the path length?

I'm sorry but I have no experience in scripts so I'm very happy that you made that pictured guidance.

**Comment by 007revad** [comment]
I meant run "Synology enable M2 volume" with it's restore option.

1. Disable your "Synology enable M2 volume" schedule so it does NOT run, and leave it disabled (you don't need it).
2. Manually run "Synology enable M2 volume" once with:
    - `"/volume2/Synology Scripts/Synology_enable_M2_volume/Synology_enable_M2_volume-1.1.21/syno_enable_M2_volume.sh" --restore`
4. Leave "Synology HDD db" scheduled to run at boot. 
5. And make sure you are using the -n option to prevent DSM updating the drive databases.
    - `"/volume2/Synology Scripts/Synology_HDD_db/Synology_HDD_db-3.5.89/syno_hdd_db.sh" -n`

**Comment by Deftone-Squad** [comment]
Ok the following drives are installed:

1. 6 x Seagate X20 20TB
2. 1 x Samsung 940 Pro SSD (just for testing)
3. 1 x Samsung 970 Pro M2

After trying several times the procedures above nothing - helped!

I make a completely clean install on one of the 2 DS1821+ and the newest DSM 7.2.1-69057 Update 5 was installed.

After that I tried the "Synology HDD db" and yes the Samsung SSD is listed as registered.
The Samsung M2 is still not registered and do NOT let me use it as a Pool or Volume.

I then added the "Synology enable M2 volume" and still do NOT let me use it as a Pool or Volume.

So to me after Update 5 both scripts do NOT helped for the M2.

**Comment by 007revad** [comment]
Does Storage Manager show the NVMe drive?

**Comment by Deftone-Squad** [comment]
Yes

**Comment by 007revad** [comment]
I just removed my HDDs from my DS1821+, installed a spare HDD and did a clean install. During the install it updated to DSM 7.2.1 Update 5. Then I manually ran `syno_hdd_db.sh -n` from Task Schedule, then closed and reopened Storage Manager and I was able to create a volume on the NVMe drive.

Can you go to "Control panel > Task Scheduler" then: 
1. Select the syno_hdd_db task,
2. Click on "Action > View Result".
3. Click on the "view details" link.
4. Click on "Copy All".
5. Paste the details into your reply.

**Comment by Deftone-Squad** [comment]
New Install only on the Samsung 940 Pro and then done the steps above:

![Screenshot 2024-05-04 112910](https://github.com/007revad/Synology_enable_M2_volume/assets/168681651/5551db36-b7ae-4624-9c4b-1190a461ea53)
![Screenshot 2024-05-04 112927](https://github.com/007revad/Synology_enable_M2_volume/assets/168681651/67518a1f-ee7b-40ce-a81a-ebc6e2604e2f)
![Screenshot 2024-05-04 112843](https://github.com/007revad/Synology_enable_M2_volume/assets/168681651/f2667659-9035-41bd-b30b-74ec839dd68a)

**Comment by 007revad** [comment]
1. Rename the `Enable HDD` folder to `Enable_HDD` so there's no space. 
2. Edit the scheduled task to replace the space with a _
3. Click on Settings and select the log folder again.

Then try the steps again.
1. Select the syno_hdd_db task,
2. Click on Run.
3. Wait a minute.
4. Select the syno_hdd_db task,
5. Click on "Action > View Result".
6. Click on the "view details" link.
7. Click on "Copy All".
8. Paste the details into your reply.

**Comment by Deftone-Squad** [comment]
Worked!

The space was the mistake...just that simple. Maybe you add a notice in your guidance, for beginner like me.

Thank you very much for your support!

**Comment by Deftone-Squad** [comment]
**Now I can post finally the result:**

Synology_HDD_db v3.5.89
DS1821+ DSM 7.2.1-69057-5 
StorageManager 1.0.0-0017

ds1821+_host_v7 version 8054

Using options: -n
Running from: /volume1/Scripts/Enable_HDD/Synology_HDD_db-3.5.89/syno_hdd_db.sh

HDD/SSD models found: 1
SSD 840 PRO Series,DXM06B0Q

M.2 drive models found: 1
Samsung SSD 970 PRO 512GB,1B2QEXP7

No M.2 PCIe cards found

No Expansion Units found

[0;33mSSD 840 PRO Series[0m already exists in [0;36mds1821+_host_v7.db[0m
[0;33mSamsung SSD 970 PRO 512GB[0m already exists in [0;36mds1821+_host_v7.db[0m

Support disk compatibility already enabled.

Support memory compatibility already enabled.

NVMe support already enabled.

M.2 volume support already enabled.

Drive db auto updates already disabled.

DSM successfully checked disk compatibility.

You may need to [0;36mreboot the Synology[0m to see the changes.

**Comment by 007revad** [comment]
I'll update the instructions.
