### ISSUE TITLE
Synostpool failed to create storage pool

### ISSUE THREAD

**Issue by kahn2k** [007revad/Synology_enable_M2_volume#188]
Hi, I'm running Esxi 7.0U3 VM DSM 7.2.1-69057 using ARC loader 24.6.29 on my Oracle X8-2L which has 8x 6.4TB F640 NVMe cards installed. They are basically rebadged Intel P4608 NVMe cards.

I've added passed through all the cards and they show up on the Synology RS4021 as dual 3.2TB each as expected (each 6.4TB are essentially 2x 3.2TB SSD) for a total on 16x in the storage manager. 

However I'm not able to get them to be used as ssd storage by running the Synology_enable_M2_volume. It errors out after the RAID and drives selection with "0 synostgpool failed to create storage pool". On the Synology storage manager, the drive requirements shows "This drive is installed via an adapter card and cannot be used in M.2 SSD  storage pools."

**Comment by 007revad** [comment]
My https://github.com/007revad/Synology_HDD_db script allows creating a volume in NVMe drives in a PCIe adaptor card (which is what "This drive is installed via an adapter card and cannot be used in M.2 SSD storage pools." is referring to).

The https://github.com/AuxXxilium/arc-addons hdddb addon is v3.5.90 of my Synology_HDD_db script.

You should only need the Synology_HDD_db script, or hdddb ARC addon, (and not the Synology_enable_M2_volume script).

**Comment by kahn2k** [comment]
Hi, it worked marvellously. Thank you.
