### ISSUE TITLE
System failed to create Storage Pool

### ISSUE THREAD

**Issue by kahn2k** [007revad/Synology_enable_M2_volume#192]
Hi, so now I'm running Proxmox 8.2.2 VM ARC loader 24.07.20 on my Oracle X8-2L which has 8x 6.4TB F640 NVMe cards installed (shows up as 16 x 3.2tb NVMe devices). They are basically rebadged Intel P4608 NVMe cards.

I've passed through the NVMe cards as PCIe devices to the VM and selected the HDD module in ARC and they all show up in DSM 7.2.1-69057U5 and I can select them for storage creation. 

However, I'm only able to select maximum 2 of the 16x 3.2TB NVMe to create each storage. Anything more and it fails with "The system failed to create Storage Pool with one of more drive (M.2 Drive 1, 1, 1, 1)".

There are no disk errors with the drives as I've created multiple  storage pools of 2x3.2TB and written and read data off them without issues.

**Comment by 007revad** [comment]
Do all your M.2 Drives really appear as M.2 Drive 1 in storage manager?

Are all 16 NVMe drives visible in storage manager?

On a real Synology they'd appear as M.2 Drive 1, M.2 Drive 2, M.2 Drive 3 and M.2 Drive 4 etc.

You can create a storage pool with an unlimited maximum number of NVMe drives (except for Basic and RAID 1) with my https://github.com/007revad/Synology_M2_volume
