### ISSUE TITLE
Error after using DTS file

### ISSUE THREAD

**Issue by bdrwu** [007revad/Synology_enable_M2_volume#196]
I'm using SA6400 model 7.2.2
NVME creates a storage pool when DTS is not used. Shut down and then on again. The storage pool is normal.
However, if you create a storage pool after compiling DTS and then shut down and then restart the storage pool, an error will occur.

The following is some information about DTS
nvme_slot@1 {
pcie_root = "0000:00:01.0,00.0,03.0,00.0";
port_type = "ssdcache";
};

nvme_slot@2 {
pcie_root = "0000:00:01.0,00.0,07.0,00.0";
port_type = "ssdcache";
};
![2024-09-17_131653](https://github.com/user-attachments/assets/55ae2ade-db42-4c06-b894-07f612b7d236)
![2024-09-17_131706](https://github.com/user-attachments/assets/484515b5-2178-4597-8f40-cdcd61b7f1ff)
![2024-09-17_131756](https://github.com/user-attachments/assets/715b1f30-7d22-4a31-862e-dab48a72daaf)

**Comment by 007revad** [comment]
Run https://github.com/007revad/Synology_HDD_db

**Comment by bdrwu** [comment]
As long as you don't use DTS files
After powering off and on, the storage pool becomes normal.
![1原先正常](https://github.com/user-attachments/assets/4187fbd2-ce78-40c1-9cac-7584c63e7a30)
![2做成存儲池](https://github.com/user-attachments/assets/393e0888-0870-4e64-ae83-22dda8ad8a06)

But add DTS file
The storage pool is wrong when shutting down and then on again.
![3重開機後錯誤](https://github.com/user-attachments/assets/bd9be10c-fddf-4ecf-a10e-319368c2442f)
![4變成不正常](https://github.com/user-attachments/assets/06c9fc9e-db11-4c90-93c4-457c1511dbc5)

The only difference between the two situations is whether or not DTS files are used.

**Comment by leotzian** [comment]
Please a little help, I thinking to add 2 m.2 unsupported to my ds1821+ to run my docker containers and my vm's 
My question is when I reboot or update dsm all my data will be lost and I have to run the db script and add them from the beginning?
This is the only thing I didn't understand 
Thanks in advance

**Comment by 007revad** [comment]
@leotzian 

You don't need syno_enable_m2 with a DS1821+ running DSM 7.2 or later. Instead just use [Synology_HDD_db](https://github.com/007revad/Synology_HDD_db) 

1. After a reboot the volume on your 3rd party NVMe drives will be okay. 
2. After a DSM update the volume on your 3rd party NVMe drives may not be mounted until after you run Synology_HDD_db again and reboot.
