### ISSUE TITLE
M2 not recognize, after upgrading to 7.2.2-72806

### ISSUE THREAD

**Issue by Geo-Thnn** [007revad/Synology_enable_M2_volume#199]
hello
using a DS920+, I used since years the M2 as a new volume, gracefully to the this script...
I have updated each time my DSM, without any problem ...
but this ultimate update is not the same ....

at the first reboot , during the update, the NAS start beeping ... nvme not recognize !

![image](https://github.com/user-attachments/assets/bdf8283f-9c32-40fe-94c7-def46769f5f7)

**Comment by 007revad** [comment]
Try https://github.com/007revad/Synology_HDD_db

**Comment by Geo-Thnn** [comment]
wonderful ... works fine

thanks a lot

**Comment by Geo-Thnn** [comment]
it works again
thanks

**Comment by huksley** [comment]
@007revad
What is the status of the Synology_enable_M2_volume, 
does it works with 7.2.2-72806 or I need to run something extra? In which version it is supported?

**Comment by 007revad** [comment]
It works with 7.2.2-72806 but you also need https://github.com/007revad/Synology_HDD_db

For newer Synology models you don't even need Synology_enable_M2_volume. Just use Synology_HDD_db

I only use Synology_HDD_db on my DS720+ and DS1821+.

**Comment by huksley** [comment]
@007revad thank you for reply!
I have DS723+
so I just uninstall  Synology_enable_M2_volume 
and install  Synology_HDD_db as a script on power up and run it, 
and after that apply an update, right?

**Comment by 007revad** [comment]
Correct.

**Comment by huksley** [comment]
Well, I've run Synology_enable_M2_volume script with -r -n flags to remove it and my Ds723+ stopped responding. Had to hard restart it.

After restart, I run Synology_HDD_db, updated and now everything works fine, thank you!
