### ISSUE TITLE
Are files deleted after a reboot or Dsm update on M.2 ?

### ISSUE THREAD

**Issue by leotzian** [007revad/Synology_enable_M2_volume#203]
Sorry for posting this way
Please a little help, I thinking to add 2 m.2 unsupported to my ds1821+ to run my docker containers and my vm's
My question is when I reboot or update dsm all my data will be lost and I have to run the db script and add them from the beginning?
This is the only thing I didn't understand
Thanks in advance

**Comment by 007revad** [comment]
@leotzian 

You don't need syno_enable_m2 with a DS1821+ running DSM 7.2 or later. Instead just use [Synology_HDD_db](https://github.com/007revad/Synology_HDD_db) 

1. After a reboot the volume on your 3rd party NVMe drives will be okay. 
2. After a DSM update the volume on your 3rd party NVMe drives still exists but storage manager will show the drives as incompatible until after you run Synology_HDD_db again and reboot.

**Comment by leotzian** [comment]
Thanks my friend very much for your quick reply, So you say when there is a dsm update and IF there is problem my files will be there and running the db script and nothing else when I reboot again all the files will be OK is this correct?
I want to buy 2 M.2 2TB each and install them as RAID 1, for safety so I install the drives run the Db script and create the volume?
After that I will install my Docker containers and my Vm's
Thanks again

**Comment by 007revad** [comment]
> Thanks my friend very much for your quick reply, So you say when there is a dsm update and IF there is problem my files will be there and running the db script and nothing else when I reboot again all the files will be OK is this correct?

Correct. 

> I want to buy 2 M.2 2TB each and install them as RAID 1, for safety so I install the drives run the Db script and create the volume?

Yes. Install the M.2 drives (while the NAS is shut down), boot the NAS, run the script, reboot, create your storage pool and volume from storage manager.

> After that I will install my Docker containers and my Vm's

Correct.

**Comment by leotzian** [comment]
@007revad  Thanks for everything you were very helpful to understand everything Thanks again have a nice New Year from Greece.
