### ISSUE TITLE
syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by 70m7E** [007revad/Synology_enable_M2_volume#39]
/volume1/data/syno_enable_m2_volume.sh: line 8: syntax error near unexpected token `newline'
/volume1/data/syno_enable_m2_volume.sh: line 8: `<!DOCTYPE html>'

**Comment by 007revad** [comment]
It sounds like you edited the script in a text editor like notepad or copied the source of the script from the website and pasted it into a text editor.

Download the script's .zip or.tar.gz archive, then extract the archive and copy the .sh file to your Synology.
https://github.com/007revad/Synology_enable_M2_volume/blob/main/images/how_to_download_generic.png
