### ISSUE TITLE
Add DS920+ DSM 7.1.1-42962 Update 5 as Not Working

### ISSUE THREAD

**Issue by leovander** [007revad/Synology_enable_M2_volume#41]
I haven't seen many issues posted here, but thought I would submit my attempt at following the directions provided.

- Model: DS920+
- DSM Version: **DSM 7.1.1-42962 Update 5**
- Synology_enable_M2_volume: **v1.0.6**
- Synology HDD db: **v2.2.45**

1. `sudo ./syno_enable_m2_volume.sh`
2. Restarted
3. Got the drive outdated database notifcation
4. Ran `sudo ./syno_hdd_db.sh --noupdate`
5. Restarted

Let me know if you any other info to add this as being confirmed as not working for **DS920+** & **DSM 7.1.1-42962 Update 5**.

**Comment by 007revad** [comment]
Thanks Leo. I've added DS920+ & DSM 7.1.1-42962 Update 5 as a NO.
