### ISSUE TITLE
Unrecognized firmware version still shows after successfully creating volume, then running syno_hdd_db.sh - normal?

### ISSUE THREAD

**Issue by thunderstorm654** [007revad/Synology_enable_M2_volume#57]
Successfully used this script to create a SHR pool with two new drives a couple of days ago. I ran the syno_hdd_db.sh script after, which got rid of the general drive warning, but noticed it still shows a message about unrecognized firmware - is this to be expected? It doesn't ping me any notifications about it, just shows in the HDD/SSD page in Storage Manager.

![image](https://github.com/007revad/Synology_enable_M2_volume/assets/16837607/45a0d9d5-4e11-4c06-a3fb-2f528d565a0b)

On another note, as you can see above, one of my drives has already crashed in the pool. This is a 3 day old drive ha ha! I'm assuming I just got a dud drive, but thought I'd mention that as well anyway in case you've heard of this happening at all when creating these volumes on 'unsupported' models. Thanks for the awesome work btw :)

Edit: the output from the db update script is as follows (I've done a reboot a couple times past few days and scheduled it also):

```
nas-ds920:~$ sudo -i "/volume1/homes/stef/scripts/syno_hdd_db.sh" --noupdate                               Password:
Synology_HDD_db v2.2.47
DS920+ DSM 7.2-64561
Using options: --noupdate

HDD/SSD models found: 2
WD160EDFZ-11AFWA0,0A81
WD160EDGZ-11B2DA0,0A85

M.2 drive models found: 1
CT500P3SSD8,P9CR30A

No M.2 cards found

No Expansion Units found

Added WD160EDFZ-11AFWA0 to ds920+_host_v7.db
Added WD160EDGZ-11B2DA0 to ds920+_host_v7.db
Added CT500P3SSD8 to ds920+_host_v7.db

Support disk compatibility already enabled.

Support memory compatibility already enabled.

M.2 volume support already enabled.

Disabled drive db auto updates.

DSM successfully checked disk compatibility.

You may need to reboot the Synology to see the changes.
```

**Comment by 007revad** [comment]
Firstly, if you ran the script previously with an earlier version of DSM and then upgraded to DSM 7.2 do **NOT** run the script with the --restore option. I'm working a fix for the issue that causes.

It does look like you got 1 faulty NVMe drive.

I wonder if DSM sees the NVMe model as "Crucial CT500P3SSD8" instead of just "CT500P3SSD8".
Can you attach a copy of your ds920+_host_v7.db file
1.  `sudo -i cp "/var/lib/disk-compatibility/ds920+_host_v7.db" "/volume1/homes/stef/scripts/ds920+_host_v7.db"`
2. Then zip the db file and attach it to your reply.

You could try running the script with:  --noupdate --force

**Comment by china-alexmercerli** [comment]
Hi Dave, my English is not very good, so I can only rely on Google Translate.
I have a little problem,
After I used the Synology_enable_M2_volume script, my M2/HDD firmware appeared Unrecognized firmware version, I used sudo -i /path-to-script/syno_hdd_db.sh --noupdate, my 8T HDD and M2 2T are normal, that is The 4T Samsung SATA HDD still has this prompt, is there a way to solve it?
Remark:
NAS: synology DS920+
system: 7.2-64561
![error](https://github.com/007revad/Synology_enable_M2_volume/assets/135486577/d46b0bb9-be62-46b5-b333-6024e79980a2)

**Comment by china-alexmercerli** [comment]
Below is the command output

Synology_HDD_db v2.2.47
DS920+ DSM 7.2-64561
Using options: -noupdate -showedits

HDD/SSD models found: 2
SSD 870 EVO 4TB,3B6Q
ST8000NM017B-2TJ103,SN02

M.2 drive models found: 1
Samsung SSD 970 EVO Plus 2TB,2B2QEXM7

No M.2 cards found

No Expansion Units found

SSD 870 EVO 4TB already exists in ds920+_host_v7.db
ST8000NM017B-2TJ103 already exists in ds920+_host_v7.db
Samsung SSD 970 EVO Plus 2TB already exists in ds920+_host_v7.db

Support disk compatibility already enabled.

Support memory compatibility already enabled.

M.2 volume support already enabled.

Drive db auto updates already disabled.

    "SSD 870 EVO 4TB": {
      "3B6Q": {
        "compatibility_interval": [
          {
            "compatibility": "support",
            "not_yet_rolling_status": "support",
            "fw_dsm_update_status_notify": false,
            "barebone_installable": true
          }
        ]
      },
      "default": {

    "ST8000NM017B-2TJ103": {
      "SN02": {
        "compatibility_interval": [
          {
            "compatibility": "support",
            "not_yet_rolling_status": "support",
            "fw_dsm_update_status_notify": false,
            "barebone_installable": true
          }
        ]
      },
      "default": {

    "Samsung SSD 970 EVO Plus 2TB": {
      "2B2QEXM7": {
        "compatibility_interval": [
          {
            "compatibility": "support",
            "not_yet_rolling_status": "support",
            "fw_dsm_update_status_notify": false,
            "barebone_installable": true
          }
        ]
      },
      "default": {

DSM successfully checked disk compatibility.

You may need to reboot the Synology to see the changes.

**Comment by 007revad** [comment]
Try the options: --noupdate --showedits --force

Can you run drive_info.sh and reply with the output:
https://github.com/007revad/Synology_HDD_db/blob/test/drive_info.sh

**Comment by china-alexmercerli** [comment]
@007revad 
Thank you for your reply

I tried the following options: --noupdate --showedits --force, it still doesn't work, but I seem to find where the problem is.

The script will change the serial number of my Samsung SATA SSD 4T to 3B6Q, but the serial number displayed in the DSM is SVT03B6Q, so I directly modify the .db file with the vi command and change it to SVT03B6Q. After restarting, the error disappears and it looks normal up.

Is it possible to directly modify it with the vi command, and will there be any risks or failures? If there is no risk, so be it.



The following is the output of the drive_info.sh command:

nvme0n1
NVMe Model: 'Samsung SSD 970 EVO Plus 2TB'
NVMe Model: 'Samsung SSD 970 EVO Plus 2TB'
NVMe Firmware: '2B2QEXM7'
NVMe Firmware: '2B2QEXM7'

sata1
Model: 'SSD'
Firmware: '3B6Q'

sata2
Model: 'ST8000NM017B-2TJ103'
Firmware: 'SN02'

**Comment by 007revad** [comment]
Good work.

I should have noticed that your screenshot showed SVT03B6Q and the command output showed 3B6Q.

Editing the db file with vi is okay.

**Comment by thunderstorm654** [comment]
> Firstly, if you ran the script previously with an earlier version of DSM and then upgraded to DSM 7.2 do **NOT** run the script with the --restore option. I'm working a fix for the issue that causes.
> 
> It does look like you got 1 faulty NVMe drive.
> 
> I wonder if DSM sees the NVMe model as "Crucial CT500P3SSD8" instead of just "CT500P3SSD8". Can you attach a copy of your ds920+_host_v7.db file
> 
> 1. `sudo -i cp "/var/lib/disk-compatibility/ds920+_host_v7.db" "/volume1/homes/stef/scripts/ds920+_host_v7.db"`
> 2. Then zip the db file and attach it to your reply.
> 
> You could try running the script with: --noupdate --force

Here's the DB file.  After zipping up I did try the --force as well but don't think it changed anything!

Thanks :)

[ds920+_host_v7.zip](https://github.com/007revad/Synology_enable_M2_volume/files/11645283/ds920%2B_host_v7.zip)

**Comment by thunderstorm654** [comment]
Also - have a replacement drive for the crashed one coming today. Will I be able to just put it in and do a repair through DSM, or will I need to re-run the volume script?

Thanks.

**Comment by 007revad** [comment]
> Will I be able to just put it in and do a repair through DSM, or will I need to re-run the volume script?

You will be able to do a repair from storage manager in DSM. You don't to run the script again.

I'll have a look at your ds920+_host_v7.db later.

**Comment by thunderstorm654** [comment]
> > Will I be able to just put it in and do a repair through DSM, or will I need to re-run the volume script?
> 
> You will be able to do a repair from storage manager in DSM. You don't to run the script again.
> 
> I'll have a look at your ds920+_host_v7.db later.

Awesome, it let me repair the volume immediately and back up and running with two :). Had to run the db update script again to get rid of unrecognized drive warning, now just back to the unrecognized firmware note against each.

**Comment by thunderstorm654** [comment]
Another update - my replacement drive has now also degraded. Same M2 slot (2). Wondering if there's something buggery about this drive model in particular (Crucial P3) or if that M2 slot on my NAS is screwy (never used it before) or if something is unhappy with the SHR raid configuration on DS920 or something else... Any recommendations? I'm thinking of trying another brand - the performance of Plex is so much better on the SSDs I can't face going back to HDD, but I can't keep replacing drives every 3 days - it's also a weird pattern they're dying in the same timeframe!

Thanks.

**Comment by thunderstorm654** [comment]
Come to the conclusion the drives are just not up to the job anyway. Going to try another model, so I'll close this for now and reopen if run into any issues with the scripts next time
 Thanks for your support and great work!

**Comment by 007revad** [comment]
After reading the comments to your post on reddit I'm glad I didn't buy any Crucial NVMe drives when I bought memory from Crucial.

**Comment by thunderstorm654** [comment]
> After reading the comments to your post on reddit I'm glad I didn't buy any Crucial NVMe drives when I bought memory from Crucial.

I know right 🤣 to be honest, it's put me off their RAM too as that was next on my list, but hopefully, that's different (!).

**Comment by 007revad** [comment]
> it's put me off their RAM too as that was next on my list, but hopefully, that's different (!

I've had no problem with their RAM. I bought 2x 16GB ECC RAM from Crucial for my DS1821+ (which was actually Micron RAM) and 4GB of Crucial RAM for my Asustor.

I did look at their NVMe drives at the same time but I was turned off by the specs and because it was TLC.
