### ISSUE TITLE
Confirmed working on DS920+

### ISSUE THREAD

**Issue by WeterPeter** [007revad/Synology_enable_M2_volume#59]
DS920+
WD Red SN700 1TB in slot 2
DSM 7.1.1-42962 Update 5

Thanks !

**Comment by scrapix** [comment]
Quick question... My NVME worked with DSM 7.1 and has data on it. 
After update to DSM 7.2 the NVME is not recognized anymore. 

With this script, will DS920+ recognize my NVME with old data again?
