### ISSUE TITLE
PVE, DS3622xs+, 7.2-64561

### ISSUE THREAD

**Issue by hawie** [007revad/Synology_enable_M2_volume#61]
use a virtual machine environment for testing convenience.

env:
PVE 7.4-3 with latest kernel: 6.2.11-2-pve
Virtual Machine: DS3622xs+ DSM 7.2-64561, PCIe passthrough:  M2. NVME

log:
Synology_enable_M2_volume v1.0.6
```
Synology_enable_M2_volume v1.0.6
DS3622xs+ DSM 7.2-64561 

Using options: 
Backup successful.

Checking file.
198666 = 3080a
0003080a: 803E 00B8 0100 0000 7524 488B

Editing file.

Checking if file was successfully edited.
198666 = 3080a
0003080a: 803E 00B8 0100 0000 9090 488B
File successfully edited.

You can now create your M.2 storage pool in Storage Manager.

M.2 volume support already enabled.

The Synology needs to restart.
Type yes to reboot now.
Type anything else to quit (if you will restart it yourself).
```

Synology_HDD_db v2.2.47
```
Synology_HDD_db v2.2.47
DS3622xs+ DSM 7.2-64561 
Using options: -nr

HDD/SSD models found: 1
HARDDISK,2.5+

M.2 drive models found: 1
aigo NVMe SSD P7000Z 2TB,H230407a

No M.2 cards found

No Expansion Units found

HARDDISK already exists in ds3622xs+_host_v7.db
aigo NVMe SSD P7000Z 2TB already exists in ds3622xs+_host_v7.db

Re-enabled support disk compatibility.

Support memory compatibility already disabled.

M.2 volume support already enabled.

Drive db auto updates already disabled.

DSM successfully checked disk compatibility.

You may need to reboot the Synology to see the changes.
```
**Issue**:
**There are 2 drives that do not meet the drive requirements.**
screenshot:
http://usa1.cyder.club/dsm2.png

additional info:
after reboot:
```
#cat /run/synostorage/disks/nvme0n1/m2_pool_support
0 
#cat /run/synostorage/disks/nvme1n1/m2_pool_support 
0
```
force, but no effect:
```
echo 1 > /run/synostorage/disks/nvme0n1/m2_pool_support
echo 1 > /run/synostorage/disks/nvme1n1/m2_pool_support
```

**Comment by 007revad** [comment]
I didn't know we could passthrough NVME drives to a VM. I think you just made my testing a lot easier.

**Comment by hawie** [comment]
SSD Cache:
http://usa1.cyder.club/ssd-cache-yes.png

Storage Pool:
http://usa1.cyder.club/no-storage-pool.png

**Comment by 007revad** [comment]
> **Issue**:
> **There are 2 drives that do not meet the drive requirements.**
> screenshot:
> http://usa1.cyder.club/dsm2.png

It looks like Synology have decided not to allow M.2 storage pools in PCIe cards. Maybe they're only blocking it on enterprise models, or maybe it's a new change in DSM 7.2.  I'll see if I can figure out how they are blocking them - because it worked in 7.2 beta.
