### ISSUE TITLE
E10M20-T1 PCIE Support

### ISSUE THREAD

**Issue by techguruz** [007revad/Synology_enable_M2_volume#62]
Any way to get E10M20-T1 PCIE support added? I have a DS2422+ with the E10M20-T1 PCIe NVMe card tried the current version on DSM 7.2 guessing only internal NVMe are supported at the minute.

**Comment by 007revad** [comment]
It should work. Did you reboot after running the script? In storage manager do the drives show as "Cache drive" or "M.2 drive"?

If you run the [Synology_HDD_db](https://github.com/007revad/Synology_HDD_db) script it will add the NVMe drives to the ds2422+_e10m20-t1_v7.db and ds2422+_v7.db drive database files.

**Comment by techguruz** [comment]
Yeah I rebooted. I have also ran the  Synology_HDD_db script. I have tried the Synology enable M2 volume which does work it would just be nicer if I could do it via the GUI on demand.

**Comment by 007revad** [comment]
Are you referring to [Synology_M2_volume](https://github.com/007revad/Synology_M2_volume) script or this [Synology_enable_M2_volume](https://github.com/007revad/Synology_enable_M2_volume) script?

Synology_enable_M2_volume lets you create and manage the storage pool and volume all from within the storage manager GUI. It works on DS3622xs+ and RS4021xs+ with DSM 7.2-64561 and DSM 7.1.1 so it should work on a DS2422+... unless DSM 7.2-64570 has changed something.

**Comment by techguruz** [comment]
The Synology_M2_volume script is working for me but the Synology_enable_m2_volume script is not working for me not sure if its the latest update since I've never tried it before or possibly because I'm using the E10M20-T1 PCIE adapter for my NVMe drives.

**Comment by 007revad** [comment]
Does Synology_HDD_db detect the E10M20-T1 and the NVMe drives?

Can you paste the output from Synology_HDD_db in a reply.

**Comment by techguruz** [comment]
Synology_HDD_db v2.2.47
DS2422+ DSM 7.2-64570 
Using options: -nr

HDD/SSD models found: 4
MG07ACA12TE,0101
WD161KFGX-68AFPN0,0A83
WDS100T1R0A-68A4W0,00WR
WDS100T1R0A-68A4W0,10WR

M.2 drive models found: 1
WD Red SN700 2000GB,112000WD

M.2 card models found: 1
E10M20-T1

No Expansion Units found

MG07ACA12TE already exists in ds2422+_host_v7.db
MG07ACA12TE already exists in ds2422+_host_v7.db.new
WD161KFGX-68AFPN0 already exists in ds2422+_host_v7.db
WD161KFGX-68AFPN0 already exists in ds2422+_host_v7.db.new
Updated WDS100T1R0A-68A4W0 to ds2422+_host_v7.db
Updated WDS100T1R0A-68A4W0 to ds2422+_host_v7.db.new
Updated WDS100T1R0A-68A4W0 to ds2422+_host_v7.db
Updated WDS100T1R0A-68A4W0 to ds2422+_host_v7.db.new
WD Red SN700 2000GB already exists in ds2422+_host_v7.db
WD Red SN700 2000GB already exists in ds2422+_host_v7.db.new
WD Red SN700 2000GB already exists in ds2422+_e10m20-t1_v7.db
WD Red SN700 2000GB already exists in ds2422+_e10m20-t1_v7.db.new

Support disk compatibility already enabled.

Support memory compatibility already disabled.

M.2 volume support already enabled.

Drive db auto updates already disabled.

DSM successfully checked disk compatibility.

You may need to reboot the Synology to see the changes.

**Comment by techguruz** [comment]
Yeah, thats what I've done for now and it is working correctly. Cheers buddy
