### ISSUE TITLE
Small scheduled task question - big thank you

### ISSUE THREAD

**Issue by Fonta** [007revad/Synology_enable_M2_volume#75]
Not an issue, just a small question and a big thank you for this script.
After updating my 1019+ to DSM 7.2-64570 Update 1 the storage pool on the m.2 disks was no longer available.
Ran this script and restarted after which the storage pool was available again.
Thanks!!

I've configured a scheduled task to run on shutdown.
My question is if it's needed to add the --noupdate after syno_hdd_db.sh or if can leave that out.
I did use --noupdate the first time running the script.

Also, would it be better to run these scripts at shutdown or at startup? I'd think on shutdown?

Current commands:
<img width="475" alt="Screenshot 2023-06-20 at 13 14 12@2x" src="https://github.com/007revad/Synology_enable_M2_volume/assets/6190791/c2d9a442-b7f5-44bc-bf71-c3d135c6897b">

**Comment by 007revad** [comment]
I would continue using the --noupdate option because without it DSM can update the drive databases whenever it wants.

**Comment by 007revad** [comment]
> Also, would it be better to run these scripts at shutdown or at startup? I'd think on shutdown?

I missed this question in my previous reply.

Originally I used to think running the scripts at shutdown was the better choice. But now I think at startup might be better.

**Comment by Fonta** [comment]
Any arguments on why that would be better?
How about running the scripts on shutdown and startup?

**Comment by 007revad** [comment]
There was one person who had the scripts scheduled to run at shutdown and they noticed that after a DSM update they had to run the run script again after it booted up.

It wouldn't hurt to run the scripts at shutdown and bootup.

**Comment by Fonta** [comment]
Configured it to run at boot and shutdown. Better safe then sorry.

Thanks for the info!
