### ISSUE TITLE
Not necessary? syno_hdd_db was enough

### ISSUE THREAD

**Issue by FBlass** [007revad/Synology_enable_M2_volume#84]
Hi,

I wanted to create a storage pool on my DS423+ with Samsung 970 Evo and a 970 Evo Plus. 
Before executing this script I used https://github.com/007revad/Synology_HDD_db which apparently was enough. 
I was already able to create a storage pool and a volume out of my two M.2 NVMe SSDs in the UI. 

I am on DSM 7.1.1-42962 Update 6. 

Anything I am missing? Anything this script here adds in functionality?

In any case thank you for your wonderful work!!

**Comment by 007revad** [comment]
The Synology_enable_M2_volume script was written before I updated [Synology_HDD_db](https://github.com/007revad/Synology_HDD_db) to enable creating M.2 volumes.

There are some Synology models where both syno_hdd_db and syno_enable_m2_volume are needed. But if syno_hdd_db works for someone then there's no need to also use syno_enable_m2_volume.

**Comment by pergolafabio** [comment]
Hey, i have an 423+ in order too , I think it officially only supports storage pool with 2 drives? Im gonna buy only one for now, then I probably still need the syno_enable_m2_volume script?

**Comment by pergolafabio** [comment]
Or is it also possible with the synology_hdd_db script only to create a storage pool?

**Comment by 007revad** [comment]
Just the synology_hdd_db script will allow you to create a storage pool on the NVMe drive(s).

**Comment by pergolafabio** [comment]
Also with 1 drive? Cause the 423+ only supports official 2 drives as storage...

**Comment by pergolafabio** [comment]
I also see this, seems not possible anymore with the HDD script only with newer DSM?
Or do you have more feedback from other users?

https://github.com/007revad/Synology_HDD_db/issues/146

**Comment by 007revad** [comment]
> Also with 1 drive? Cause the 423+ only supports official 2 drives as storage...

DSM supports 1 or 2 NVMe drives as storage.

The hdd_db script works in DSM 7.21 including update 1 to update 4.

**Comment by 007revad** [comment]
> I also see this, seems not possible anymore with the HDD script only with newer DSM? Or do you have more feedback from other users?
> 
> [007revad/Synology_HDD_db#146](https://github.com/007revad/Synology_HDD_db/issues/146)

That person used the syno_create_m2_volume script which is not needed, or recommended, for '21 series or newer models using DSM 7.2 or newer.
