### ISSUE TITLE
cancel script Synology_enable_M2_volume

### ISSUE THREAD

**Issue by vensikmay** [007revad/Synology_enable_M2_volume#92]
how can i cancel the script?

**Comment by 007revad** [comment]
Do you mean undo the changes it made? You can run the script with the --restore option.
`sudo -i /volume1/scripts/syno_enable_m2_volume.sh --restore`

Or cancel it while it is running? Pressing Ctrl+C will stop a script or command.

**Comment by vensikmay** [comment]
Thank you. happened
