### ISSUE TITLE
DS923+ already succeed with Synology_M2_volume, should I run this Synology_enable_M2_volume?

### ISSUE THREAD

**Issue by uliod** [007revad/Synology_enable_M2_volume#93]
Hi 007revad, BIG thanks for sharing these great scripts, as I have already run Synology_M2_volume script last weekend on my DS923+, and successfully created volume with my 2T West Digital NVMe drive. 

Now I am planning to add one more NVMe drive to DS923+, as it has two NVMe slots. My plan is to bind these two drives and create a 4T pool as a whole, instead of two separate 2T volumes. But I am not sure what to do with that... It seems I have to run this new Synology_enable_M2_volume script and then choose the JBOD mode in Disk Manager, is that correct? And do I need to erase the previous Synology_M2_volume script before I run the new one? 

Many thanks!

Chris

**Comment by 007revad** [comment]
Sorry, somehow I didn't see this issue until now.

You've probably answered your own question by now. You are correct. I'd use the Synology_enable_M2_volume script and then choose the JBOD mode in Disk Manager.
